# Generated by Django 4.0.4 on 2022-05-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_delete_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
