# Generated by Django 4.0.4 on 2022-05-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_user_country_remove_user_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='delete',
        ),
        migrations.DeleteModel(
            name='update',
        ),
    ]
