# Generated by Django 4.0.4 on 2022-05-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_validform_rename_fname_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='password',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='validform',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='validform',
            old_name='comment',
            new_name='pasword',
        ),
    ]
