# Generated by Django 4.0.4 on 2022-05-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_rename_password_contact_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validform',
            old_name='pasword',
            new_name='password',
        ),
    ]
